### PR TITLE
Update zoomScale when minimumZoomScale value changed. Instead of `setIni...

### PR DESCRIPTION
**Pull request by heistings**
...tialZoomScale`.

Signed-off-by: 庞博 <bopang@sohu-inc.com>

### CODE REVIEW

**Comment by heistings** [comment]
I think it may be better to update zoomScale of RSKImageScrollView when minimumZoomScale value changed. Instead of calculate again in `setInitialZoomScale` after `setMaxMinZoomScalesForCurrentBounds`.

**Comment by ruslanskorb** [comment]
Hi @heistings,

Thanks for the PR!
But it will not work properly in all cases.
For example, after resizing we update `minimumZoomScale`, but `zoomScale` should not be changed at this time.

Sincerely,
Ruslan

**Comment by heistings** [comment]
I'm sorry, I don't understand very well. Such as the `minimumZoomScale` was calculated as 1.2 after resizing, and the `zoomScale` was initialized as 1.0, and we should not update `zoomScale` to 1.2?

**Comment by ruslanskorb** [comment]
The method [`recoverFromResizing`](https://github.com/ruslanskorb/RSKImageCropper/blob/master/RSKImageCropper/RSKImageScrollView.m#L268-296) takes care of this.
You can try to zoom in, and then rotate the device. So you see the problem.

**Comment by heistings** [comment]
Then what if:
```objective-c
    if (self.zoomScale < self.minimumZoomScale) {
        self.zoomScale = self.minimumZoomScale;
    }
```

**Comment by heistings** [comment]
I see the problem even with the origin master code.
img_5468
img_5469

**Comment by ruslanskorb** [comment]
```objective-c
if (self.zoomScale < self.minimumZoomScale) {
    self.zoomScale = self.minimumZoomScale;
}
```

In this case, the initial zoom scale will be incorrect (1).

**Comment by ruslanskorb** [comment]
What the problem do you see on the image above?

**Comment by heistings** [comment]
The crop area changed when rotate the device. I discover that we are not focus on the same problem, and what is the problem you mean `You can try to zoom in, and then rotate the device. So you see the problem.`?

**Comment by heistings** [comment]
Thank you, I just found out my bug, if minimumZoomScale was set from 1.0 to 0.2, the zoomScale should be changed. My original purpose is to remove the "duplicated code" below:
```objective-c
    CGSize boundsSize = self.bounds.size;
    CGFloat xScale = boundsSize.width  / _imageSize.width;    // the scale needed to perfectly fit the image width-wise
    CGFloat yScale = boundsSize.height / _imageSize.height;   // the scale needed to perfectly fit the image height-wise
    CGFloat scale = MAX(xScale, yScale);

```

**Comment by ruslanskorb** [comment]
On the first gif we can see the extra zoom. This is the problem I had in mind.

**Comment by heistings** [comment]
Cool! I mean the problem will occur on the origin code.

**Comment by ruslanskorb** [comment]
It's hard to explain in words. Please run and compare [this](https://github.com/heistings/RSKImageCropper/tree/dev_setInitialZoomScale/RSKImageCropper) and [this](https://github.com/ruslanskorb/RSKImageCropper).

**Comment by heistings** [comment]
@ruslanskorb You are right.

**Comment by ruslanskorb** [comment]
@heistings Thank you for your striving to make RSKImageCropper better! :+1:

**Pull request closed without merging**
