### PR TITLE
Add framework and Carthage support

### PR DESCRIPTION
**Pull request by hankbao**

### CODE REVIEW

**Comment by ruslanskorb** [comment]
screen shot 2015-06-18 at 9 54 59 pm

**Comment by pronebird** [comment]
I suppose this import will only work on framework.

**Comment by hankbao** [comment]
Oops... my bad. I've fixed that import statement and also updated the missing visibility settings of framework headers in f97786b.

**Comment by hankbao** [comment]
It seems there are still some building issues with the newly added protected header importing statement in the framework umbrella header. However, that protected header should be put there if we need to expose it to the framework users as I understand. Or should I mark it as the private header of the framework?

**Comment by hankbao** [comment]
As Travis CI is happy with recent commits now, hopefully this pr could be merged.

**Comment by abbysingh** [comment]
Hey is carthage support available in master now?

**Pull request closed without merging**
