### PR TITLE
Fix crop rotated images

### PR DESCRIPTION
**Pull request by Konshin**

### CODE REVIEW

**Comment by ruslanskorb** [comment]
@Konshin Sorry for my misunderstanding, but what are you trying to fix? As far as I can see, your code calculates an incorrect `cropRect`.

**Comment by Konshin** [comment]
When i try to crop custom rect (`RSKImageCropModeCustom`) from rotated image (`imageCropVC.rotationEnabled = YES`) i see white areas, that cut the picture around the edges
http://take.ms/fafJv 
I use your example and with adding dataSource to RSKImageCropViewController
```
- (void)onAddPhotoButtonTouch:(UIButton *)sender
{
    UIImage *photo = [UIImage imageNamed:@"photo"];
    RSKImageCropViewController *imageCropVC = [[RSKImageCropViewController alloc] initWithImage:photo cropMode:RSKImageCropModeCustom];
    imageCropVC.rotationEnabled = YES;
    imageCropVC.dataSource = self;
    imageCropVC.delegate = self;
    [self.navigationController pushViewController:imageCropVC animated:YES];
}

#pragma mark - RSKImageCropViewControllerDataSource

- (CGRect)imageCropViewControllerCustomMaskRect:(RSKImageCropViewController *)controller {
    CGSize rectSize = CGSizeMake(300, 150);
    return CGRectMake((controller.view.bounds.size.width - rectSize.width) / 2,
                      (controller.view.bounds.size.height - rectSize.height) / 2,
                      rectSize.width,
                      rectSize.height);
}

- (UIBezierPath *)imageCropViewControllerCustomMaskPath:(RSKImageCropViewController *)controller {
    CGRect rect = [self imageCropViewControllerCustomMaskRect:controller];
    return [UIBezierPath bezierPathWithRect:rect];
}
```

**Comment by ruslanskorb** [comment]
@Konshin If you want to support the rotation  when `cropMode` is `RSKImageCropModeCustom` you must implement `imageCropViewControllerCustomMovementRect:` method. The mask is applied on top of the movement rect.

**Comment by Konshin** [comment]
if i use `imageCropViewControllerCustomMovementRect` i can't crop image at edges - scroll to edge not available (bouncing back)

**Comment by ruslanskorb** [comment]
@Konshin You need to calculate and return the valid movement rect.

**Comment by Konshin** [comment]
Ok, thanks. Will try

**Pull request closed without merging**
